### ISSUE TITLE
Proposal to translate your themes and plugin in Italian, Spanish, French

### ISSUE THREAD

**Issue by wocmultimedia** [alinacsava/visual-coffee-free-theme#1]
I don't find any email or form because your website is down or not reachable, so I write here my offer.

Dear Sirs,

I visited your website and I'm writing to propose you the translation of your themes and plugins in Italian, Spanish and French.

I'am an Editor (PTE) for different wordpress plugins (Falang, Falang Importer, Paid Membership Pro, Kadence Block, Elementor, MapsMarker pro). As well as I'm translating all premium themes of kadencewp.com and also software of animation and presentation (Saola animate, Active Presenter by atomisystems.com).

Well, if you are interested the cost for each language is 100 € (a hundred Euros) per theme. In case of several themes in different languages we can make a better offer upon agreement.

Looking forward to hearing from you soon.

Your faithfully,
Angelo Giammarresi
World On Communications - Italy
websites:
https://www.wocmultimedia.biz

**Comment by alinacsava** [comment]
Hi. The theme is available on wordpress.org at https://wordpress.org/themes/visual-coffee/ and can be translated only there. It already has multiple translations https://translate.wordpress.org/projects/wp-themes/visual-coffee/ including Spanish.
